spring:
  application:
    name: ridehailing-backend

  datasource:
    url: jdbc:postgresql://localhost:5438/ridehailing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ridehailing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  websocket:
    allowed-origins: "*"

# JWT
app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000        # 24 hours in ms
    refresh-expiration: 604800000  # 7 days in ms

  # Paystack
  paystack:
    secret-key: ${PAYSTACK_SECRET_KEY:sk_test_34e7df8065fb09e507319eb3bc3fbb4911bd7e0e}
    base-url: https://api.paystack.co

  # Termii
  termii:
    api-key: ${TERMII_API_KEY:your-termii-api-key}
    base-url: https://api.ng.termii.com
    sender-id: RideHailing

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

server:
  port: 8080